Public Class ErrorCode
    Public Enum EN_ERROR_CODE
        ERROR_CODE_SUCCESS = 0
        ERROR_FILE_NOT_EXISTS = 1
        ERROR_FILE_OPEN_REPORT_SHEET
        ERROR_IN_WRITE_REPORT_TO_DB
        ERROR_IN_WRITE_REPORT_DATA

        ERROR_IN_OPEN_MEMBERS_SHEET
        ERROR_IN_WRITE_MEMBERS_TO_DB
        ERROR_IN_WRITE_MEMBERS_DATA

        ERROR_IN_OPEN_DB_CONNECTION
        ERROR_IN_WRITE_CVSDATA_TO_DB
        ERROR_IN_GET_USER_IDS
    End Enum
End Class
